# Generated by Django 3.2.13 on 2022-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
